### PR TITLE
Fix create account bugs

### LINKED ISSUE #176: [PE-D] Able to create an account with username `admin` and password `admin` while it’s supposed not to
Creating a new account and put the username as `admin` and password as `admin`:  
Username: `admin`  
Password: `admin`  
Name: `admin`  
MCR: `MA1101N`

It will redirect straight into the app (this makes me intuitively think that I can create a doctor account successfully with username and password being `admin` while it is supposed not to be the case):

Then I go to one patient’s data and attempt to add a note:
`access 1`
`addnote c/ Test note`

It appears that I can’t add note since I do not have the `doctor` role (so I’m currently the `admin`)

Perhaps you guys might want to limit the account `admin` being exclusively available to the administrative staff, such that no new account with username `admin` can be created.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: ducbinh2611/ped#2

### LINKED ISSUE #177: [PE-D] Able to create a new doctor account with username `admin`
This is somewhat related to the bug of creating a new user with `admin` as both username and password previously. But now if I create a new account using a different password (ensured that there is no account with username `admin` created before):  

Username: `admin`
Password: `admintest` (anything that is different from `admin`)
Name: `admin`
MCR: `MN1101S`

It will redirect me directly to the main window of the app (so I assume the creation of account is successful)

I can indeed add notes to patient's profile using this account:
`access 1`
`addnote c/ Test note #2`

So this is a doctor account with the username `admin`, which exists alongside with the admin staff account with username `admin`. I feel that is a bit weird that’s each account's `username` should be unique but I can create a new account with username `admin`

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: ducbinh2611/ped#3

### PR DESCRIPTION
**Pull request by PrestonTYR**
Resolves #176 
Resolves #177 
not sure about #199

### CODE REVIEW

File: src/main/java/seedu/medibook/storage/JsonUserAccountsListStorage.java [hunk 1]
```diff
@@ -75,14 +68,26 @@ public void createAccount(String username, String password, String doctorName, S
...
+        }
+
+        if (!Mcr.isValidMcr(doctorMcr)) {
+            throw new IllegalValueException(Mcr.MESSAGE_CONSTRAINTS);
+        }
+
         Account newAccount = new Account(username, password, new Doctor(new Name(doctorName), new Mcr(doctorMcr)));
 
+        if (newAccount.getUsername().equals("admin")) {
+            throw new IllegalValueException("Username already exists");
```
Comment (Wong-ZZ) [inline src/main/java/seedu/medibook/storage/JsonUserAccountsListStorage.java]: Shouldn't both `"admin"` and the error message be abstracted out?

File: src/main/java/seedu/medibook/storage/JsonUserAccountsListStorage.java [hunk 2]
```diff
@@ -75,14 +68,26 @@ public void createAccount(String username, String password, String doctorName, S
...
+        }
+
         if (FileUtil.isFileExists(filepath)) {
             JsonSerializableUserAccountsList jsonUserAccountList = JsonUtil.readJsonFile(
                     filepath, JsonSerializableUserAccountsList.class).get();
             UserAccountsList accountsList = jsonUserAccountList.toModelType();
 
-            if (accountsList.usernameExists(newAccount) || newAccount.getUsername().equals("admin")) {
+            if (accountsList.usernameExists(newAccount)) {
                 throw new IllegalValueException("Username already exists");
```
Comment (Wong-ZZ) [inline src/main/java/seedu/medibook/storage/JsonUserAccountsListStorage.java]: Same as above

**Review by Wong-ZZ — APPROVED** [review]
lgtm
