### PR TITLE
Replace dummy medical note list UI with actual medical note list and fix invalid date bug (Order: 3)

### LINKED ISSUE #145: Fix invalid date bug
Program currently allows invalid date like 31-04-2020 or 29-02-2019 to be parsed.

### PR DESCRIPTION
**Pull request by wang-jun-hao**
Implement inner list in MedicalNoteList as an ObservableList
Fix invalid date bug, Fixes #145 
Privatise Date internal fields

### CODE REVIEW

File: src/main/java/seedu/medibook/model/medicalnote/MedicalNoteList.java [hunk 1]
```diff
@@ -4,18 +4,21 @@
...
+import javafx.collections.FXCollections;
+import javafx.collections.ObservableList;
+
 /**
  * Represents a list of medical notes for a Patient in MediBook.
  */
 public class MedicalNoteList implements ReadOnlyMedicalNoteList {
     private static final MedicalNoteComparator comparator = new MedicalNoteComparator();
-    private final List<MedicalNote> innerList;
+    private final ObservableList<MedicalNote> innerList;
```
Comment (foojingyi) [inline src/main/java/seedu/medibook/model/medicalnote/MedicalNoteList.java:16]: Maybe add a JavaDoc comment (single line "/** comment here */) to describe innerList?

**Review by foojingyi — APPROVED** [review]
Just a tiny comment, lgtm 👍

File: src/main/java/seedu/medibook/model/medicalnote/MedicalNoteList.java (hunk 1 above)
Comment (wang-jun-hao) [reply src/main/java/seedu/medibook/model/medicalnote/MedicalNoteList.java:16]: Resolved
